/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface MediaAsset {
  'id' : bigint,
  'size' : bigint,
  'mimeType' : string,
  'filename' : string,
  'blobId' : string,
  'uploadedAt' : bigint,
  'uploadedBy' : Principal,
}
export interface UserProfile {
  'name' : string,
  'email' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Visit {
  'id' : string,
  'referrer' : string,
  'visitedAt' : bigint,
  'pageUrl' : string,
  'deviceType' : string,
  'browser' : string,
  'sessionId' : string,
  'userAgent' : string,
  'ipAddress' : string,
}
export interface VisitorSession {
  'lastActivity' : bigint,
  'isOnline' : boolean,
  'firstVisit' : bigint,
  'sessionId' : string,
  'ipAddress' : string,
}
export interface VisitorStats {
  'visitorsThisWeek' : bigint,
  'visitorsYesterday' : bigint,
  'visitorsThisYear' : bigint,
  'onlineNow' : bigint,
  'totalVisitors' : bigint,
  'visitorsToday' : bigint,
  'pageViewsToday' : bigint,
  'visitorsThisMonth' : bigint,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'cleanupExpiredSessions' : ActorMethod<[], undefined>,
  'deleteMediaAsset' : ActorMethod<[bigint], undefined>,
  'getAllMediaAssets' : ActorMethod<[], Array<MediaAsset>>,
  'getAllVisitorSessions' : ActorMethod<[], Array<VisitorSession>>,
  'getAllVisits' : ActorMethod<[], Array<Visit>>,
  'getAssetsByDateRange' : ActorMethod<[bigint, bigint], Array<MediaAsset>>,
  'getAssetsByUploader' : ActorMethod<[Principal], Array<MediaAsset>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMediaAssetByBlobId' : ActorMethod<[string], [] | [MediaAsset]>,
  'getMediaAssetById' : ActorMethod<[bigint], [] | [MediaAsset]>,
  'getOnlineUsers' : ActorMethod<[], bigint>,
  'getStableVisitorStats' : ActorMethod<[], VisitorStats>,
  'getTotalPageViews' : ActorMethod<[], bigint>,
  'getTotalVisitors' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVisitorStats' : ActorMethod<[], VisitorStats>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'periodicCleanup' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'trackVisitor' : ActorMethod<
    [string, string, string, string, string, string, string],
    undefined
  >,
  'updateMediaAsset' : ActorMethod<[bigint, string, string], undefined>,
  'uploadMediaAsset' : ActorMethod<
    [string, string, string, string, bigint],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];