/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const MediaAsset = IDL.Record({
  'id' : IDL.Nat,
  'size' : IDL.Nat,
  'mimeType' : IDL.Text,
  'filename' : IDL.Text,
  'blobId' : IDL.Text,
  'uploadedAt' : IDL.Int,
  'uploadedBy' : IDL.Principal,
});
export const VisitorSession = IDL.Record({
  'lastActivity' : IDL.Int,
  'isOnline' : IDL.Bool,
  'firstVisit' : IDL.Int,
  'sessionId' : IDL.Text,
  'ipAddress' : IDL.Text,
});
export const Visit = IDL.Record({
  'id' : IDL.Text,
  'referrer' : IDL.Text,
  'visitedAt' : IDL.Int,
  'pageUrl' : IDL.Text,
  'deviceType' : IDL.Text,
  'browser' : IDL.Text,
  'sessionId' : IDL.Text,
  'userAgent' : IDL.Text,
  'ipAddress' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const VisitorStats = IDL.Record({
  'visitorsThisWeek' : IDL.Nat,
  'visitorsYesterday' : IDL.Nat,
  'visitorsThisYear' : IDL.Nat,
  'onlineNow' : IDL.Nat,
  'totalVisitors' : IDL.Nat,
  'visitorsToday' : IDL.Nat,
  'pageViewsToday' : IDL.Nat,
  'visitorsThisMonth' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'cleanupExpiredSessions' : IDL.Func([], [], []),
  'deleteMediaAsset' : IDL.Func([IDL.Nat], [], []),
  'getAllMediaAssets' : IDL.Func([], [IDL.Vec(MediaAsset)], ['query']),
  'getAllVisitorSessions' : IDL.Func([], [IDL.Vec(VisitorSession)], ['query']),
  'getAllVisits' : IDL.Func([], [IDL.Vec(Visit)], ['query']),
  'getAssetsByDateRange' : IDL.Func(
      [IDL.Int, IDL.Int],
      [IDL.Vec(MediaAsset)],
      ['query'],
    ),
  'getAssetsByUploader' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(MediaAsset)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMediaAssetByBlobId' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(MediaAsset)],
      ['query'],
    ),
  'getMediaAssetById' : IDL.Func([IDL.Nat], [IDL.Opt(MediaAsset)], ['query']),
  'getOnlineUsers' : IDL.Func([], [IDL.Nat], ['query']),
  'getStableVisitorStats' : IDL.Func([], [VisitorStats], ['query']),
  'getTotalPageViews' : IDL.Func([], [IDL.Nat], ['query']),
  'getTotalVisitors' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVisitorStats' : IDL.Func([], [VisitorStats], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'periodicCleanup' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'trackVisitor' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateMediaAsset' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
  'uploadMediaAsset' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const MediaAsset = IDL.Record({
    'id' : IDL.Nat,
    'size' : IDL.Nat,
    'mimeType' : IDL.Text,
    'filename' : IDL.Text,
    'blobId' : IDL.Text,
    'uploadedAt' : IDL.Int,
    'uploadedBy' : IDL.Principal,
  });
  const VisitorSession = IDL.Record({
    'lastActivity' : IDL.Int,
    'isOnline' : IDL.Bool,
    'firstVisit' : IDL.Int,
    'sessionId' : IDL.Text,
    'ipAddress' : IDL.Text,
  });
  const Visit = IDL.Record({
    'id' : IDL.Text,
    'referrer' : IDL.Text,
    'visitedAt' : IDL.Int,
    'pageUrl' : IDL.Text,
    'deviceType' : IDL.Text,
    'browser' : IDL.Text,
    'sessionId' : IDL.Text,
    'userAgent' : IDL.Text,
    'ipAddress' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const VisitorStats = IDL.Record({
    'visitorsThisWeek' : IDL.Nat,
    'visitorsYesterday' : IDL.Nat,
    'visitorsThisYear' : IDL.Nat,
    'onlineNow' : IDL.Nat,
    'totalVisitors' : IDL.Nat,
    'visitorsToday' : IDL.Nat,
    'pageViewsToday' : IDL.Nat,
    'visitorsThisMonth' : IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'cleanupExpiredSessions' : IDL.Func([], [], []),
    'deleteMediaAsset' : IDL.Func([IDL.Nat], [], []),
    'getAllMediaAssets' : IDL.Func([], [IDL.Vec(MediaAsset)], ['query']),
    'getAllVisitorSessions' : IDL.Func(
        [],
        [IDL.Vec(VisitorSession)],
        ['query'],
      ),
    'getAllVisits' : IDL.Func([], [IDL.Vec(Visit)], ['query']),
    'getAssetsByDateRange' : IDL.Func(
        [IDL.Int, IDL.Int],
        [IDL.Vec(MediaAsset)],
        ['query'],
      ),
    'getAssetsByUploader' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(MediaAsset)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMediaAssetByBlobId' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(MediaAsset)],
        ['query'],
      ),
    'getMediaAssetById' : IDL.Func([IDL.Nat], [IDL.Opt(MediaAsset)], ['query']),
    'getOnlineUsers' : IDL.Func([], [IDL.Nat], ['query']),
    'getStableVisitorStats' : IDL.Func([], [VisitorStats], ['query']),
    'getTotalPageViews' : IDL.Func([], [IDL.Nat], ['query']),
    'getTotalVisitors' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVisitorStats' : IDL.Func([], [VisitorStats], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'periodicCleanup' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'trackVisitor' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateMediaAsset' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
    'uploadMediaAsset' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };