/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ArticleComment {
  'id' : bigint,
  'content' : string,
  'userId' : Principal,
  'articleId' : bigint,
  'timestamp' : bigint,
}
export interface ContactSubmission {
  'id' : bigint,
  'userId' : [] | [Principal],
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : bigint,
}
export interface CreditSimulation {
  'id' : bigint,
  'userId' : Principal,
  'term' : bigint,
  'timestamp' : bigint,
  'amount' : bigint,
  'vehicleId' : bigint,
}
export interface ProductLike {
  'id' : bigint,
  'userId' : Principal,
  'timestamp' : bigint,
  'vehicleId' : bigint,
}
export interface UserProfile {
  'name' : string,
  'email' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Vehicle {
  'id' : bigint,
  'vehicleName' : string,
  'publishStatus' : boolean,
  'description' : string,
  'basePrice' : bigint,
}
export interface VisitorStats {
  'totalVisitors' : bigint,
  'weeklyVisitors' : bigint,
  'monthlyVisitors' : bigint,
  'dailyVisitors' : bigint,
  'pageViews' : bigint,
}
export interface WebsiteSettings {
  'id' : bigint,
  'dealerAddress' : string,
  'operationalHours' : string,
  'instagramUrl' : string,
  'siteName' : string,
  'contactEmail' : string,
  'contactWhatsapp' : string,
  'youtubeUrl' : string,
  'facebookUrl' : string,
  'contactPhone' : string,
  'tiktokUrl' : string,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addArticleComment' : ActorMethod<[bigint, string], bigint>,
  'addVehicle' : ActorMethod<[Vehicle], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCreditSimulation' : ActorMethod<[bigint, bigint, bigint], bigint>,
  'deleteArticleComment' : ActorMethod<[bigint], undefined>,
  'deleteVehicle' : ActorMethod<[bigint], undefined>,
  'getAllContactSubmissions' : ActorMethod<[], Array<ContactSubmission>>,
  'getAllCreditSimulations' : ActorMethod<[], Array<CreditSimulation>>,
  'getAllVehiclePreviews' : ActorMethod<[], Array<Vehicle>>,
  'getAllVehiclesAdmin' : ActorMethod<[], Array<Vehicle>>,
  'getArticleComments' : ActorMethod<[bigint], Array<ArticleComment>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMyCreditSimulations' : ActorMethod<[], Array<CreditSimulation>>,
  'getProductLikes' : ActorMethod<[bigint], Array<ProductLike>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVehicle' : ActorMethod<[bigint], [] | [Vehicle]>,
  'getVehicleAdmin' : ActorMethod<[bigint], [] | [Vehicle]>,
  'getVisitorStats' : ActorMethod<[], VisitorStats>,
  'getWebsiteSettings' : ActorMethod<[bigint], [] | [WebsiteSettings]>,
  'incrementPageView' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'likeProduct' : ActorMethod<[bigint], bigint>,
  'resetVisitorStats' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveWebsiteSettings' : ActorMethod<[WebsiteSettings], undefined>,
  'submitContactForm' : ActorMethod<[string, string, string], bigint>,
  'unlikeProduct' : ActorMethod<[bigint], undefined>,
  'updateVehicle' : ActorMethod<[bigint, Vehicle], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];