/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Vehicle = IDL.Record({
  'id' : IDL.Nat,
  'vehicleName' : IDL.Text,
  'publishStatus' : IDL.Bool,
  'description' : IDL.Text,
  'basePrice' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ContactSubmission = IDL.Record({
  'id' : IDL.Nat,
  'userId' : IDL.Opt(IDL.Principal),
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const CreditSimulation = IDL.Record({
  'id' : IDL.Nat,
  'userId' : IDL.Principal,
  'term' : IDL.Nat,
  'timestamp' : IDL.Int,
  'amount' : IDL.Nat,
  'vehicleId' : IDL.Nat,
});
export const ArticleComment = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'userId' : IDL.Principal,
  'articleId' : IDL.Nat,
  'timestamp' : IDL.Int,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const ProductLike = IDL.Record({
  'id' : IDL.Nat,
  'userId' : IDL.Principal,
  'timestamp' : IDL.Int,
  'vehicleId' : IDL.Nat,
});
export const VisitorStats = IDL.Record({
  'totalVisitors' : IDL.Nat,
  'weeklyVisitors' : IDL.Nat,
  'monthlyVisitors' : IDL.Nat,
  'dailyVisitors' : IDL.Nat,
  'pageViews' : IDL.Nat,
});
export const WebsiteSettings = IDL.Record({
  'id' : IDL.Nat,
  'dealerAddress' : IDL.Text,
  'operationalHours' : IDL.Text,
  'instagramUrl' : IDL.Text,
  'siteName' : IDL.Text,
  'contactEmail' : IDL.Text,
  'contactWhatsapp' : IDL.Text,
  'youtubeUrl' : IDL.Text,
  'facebookUrl' : IDL.Text,
  'contactPhone' : IDL.Text,
  'tiktokUrl' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addArticleComment' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
  'addVehicle' : IDL.Func([Vehicle], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCreditSimulation' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'deleteArticleComment' : IDL.Func([IDL.Nat], [], []),
  'deleteVehicle' : IDL.Func([IDL.Nat], [], []),
  'getAllContactSubmissions' : IDL.Func(
      [],
      [IDL.Vec(ContactSubmission)],
      ['query'],
    ),
  'getAllCreditSimulations' : IDL.Func(
      [],
      [IDL.Vec(CreditSimulation)],
      ['query'],
    ),
  'getAllVehiclePreviews' : IDL.Func([], [IDL.Vec(Vehicle)], ['query']),
  'getAllVehiclesAdmin' : IDL.Func([], [IDL.Vec(Vehicle)], ['query']),
  'getArticleComments' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(ArticleComment)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMyCreditSimulations' : IDL.Func(
      [],
      [IDL.Vec(CreditSimulation)],
      ['query'],
    ),
  'getProductLikes' : IDL.Func([IDL.Nat], [IDL.Vec(ProductLike)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVehicle' : IDL.Func([IDL.Nat], [IDL.Opt(Vehicle)], ['query']),
  'getVehicleAdmin' : IDL.Func([IDL.Nat], [IDL.Opt(Vehicle)], ['query']),
  'getVisitorStats' : IDL.Func([], [VisitorStats], ['query']),
  'getWebsiteSettings' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(WebsiteSettings)],
      ['query'],
    ),
  'incrementPageView' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'likeProduct' : IDL.Func([IDL.Nat], [IDL.Nat], []),
  'resetVisitorStats' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveWebsiteSettings' : IDL.Func([WebsiteSettings], [], []),
  'submitContactForm' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
  'unlikeProduct' : IDL.Func([IDL.Nat], [], []),
  'updateVehicle' : IDL.Func([IDL.Nat, Vehicle], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Vehicle = IDL.Record({
    'id' : IDL.Nat,
    'vehicleName' : IDL.Text,
    'publishStatus' : IDL.Bool,
    'description' : IDL.Text,
    'basePrice' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ContactSubmission = IDL.Record({
    'id' : IDL.Nat,
    'userId' : IDL.Opt(IDL.Principal),
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const CreditSimulation = IDL.Record({
    'id' : IDL.Nat,
    'userId' : IDL.Principal,
    'term' : IDL.Nat,
    'timestamp' : IDL.Int,
    'amount' : IDL.Nat,
    'vehicleId' : IDL.Nat,
  });
  const ArticleComment = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'userId' : IDL.Principal,
    'articleId' : IDL.Nat,
    'timestamp' : IDL.Int,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const ProductLike = IDL.Record({
    'id' : IDL.Nat,
    'userId' : IDL.Principal,
    'timestamp' : IDL.Int,
    'vehicleId' : IDL.Nat,
  });
  const VisitorStats = IDL.Record({
    'totalVisitors' : IDL.Nat,
    'weeklyVisitors' : IDL.Nat,
    'monthlyVisitors' : IDL.Nat,
    'dailyVisitors' : IDL.Nat,
    'pageViews' : IDL.Nat,
  });
  const WebsiteSettings = IDL.Record({
    'id' : IDL.Nat,
    'dealerAddress' : IDL.Text,
    'operationalHours' : IDL.Text,
    'instagramUrl' : IDL.Text,
    'siteName' : IDL.Text,
    'contactEmail' : IDL.Text,
    'contactWhatsapp' : IDL.Text,
    'youtubeUrl' : IDL.Text,
    'facebookUrl' : IDL.Text,
    'contactPhone' : IDL.Text,
    'tiktokUrl' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addArticleComment' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
    'addVehicle' : IDL.Func([Vehicle], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCreditSimulation' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'deleteArticleComment' : IDL.Func([IDL.Nat], [], []),
    'deleteVehicle' : IDL.Func([IDL.Nat], [], []),
    'getAllContactSubmissions' : IDL.Func(
        [],
        [IDL.Vec(ContactSubmission)],
        ['query'],
      ),
    'getAllCreditSimulations' : IDL.Func(
        [],
        [IDL.Vec(CreditSimulation)],
        ['query'],
      ),
    'getAllVehiclePreviews' : IDL.Func([], [IDL.Vec(Vehicle)], ['query']),
    'getAllVehiclesAdmin' : IDL.Func([], [IDL.Vec(Vehicle)], ['query']),
    'getArticleComments' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(ArticleComment)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMyCreditSimulations' : IDL.Func(
        [],
        [IDL.Vec(CreditSimulation)],
        ['query'],
      ),
    'getProductLikes' : IDL.Func([IDL.Nat], [IDL.Vec(ProductLike)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVehicle' : IDL.Func([IDL.Nat], [IDL.Opt(Vehicle)], ['query']),
    'getVehicleAdmin' : IDL.Func([IDL.Nat], [IDL.Opt(Vehicle)], ['query']),
    'getVisitorStats' : IDL.Func([], [VisitorStats], ['query']),
    'getWebsiteSettings' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(WebsiteSettings)],
        ['query'],
      ),
    'incrementPageView' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'likeProduct' : IDL.Func([IDL.Nat], [IDL.Nat], []),
    'resetVisitorStats' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveWebsiteSettings' : IDL.Func([WebsiteSettings], [], []),
    'submitContactForm' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'unlikeProduct' : IDL.Func([IDL.Nat], [], []),
    'updateVehicle' : IDL.Func([IDL.Nat, Vehicle], [], []),
  });
};

export const init = ({ IDL }) => { return []; };