/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const BlogPost = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'authorId' : IDL.Principal,
  'published' : IDL.Bool,
  'createdAt' : IDL.Int,
  'publishedAt' : IDL.Opt(IDL.Int),
  'updatedAt' : IDL.Int,
  'excerpt' : IDL.Text,
  'imageId' : IDL.Opt(IDL.Text),
});
export const Variant = IDL.Record({
  'id' : IDL.Nat,
  'displayOrder' : IDL.Nat,
  'name' : IDL.Text,
  'overridePrice' : IDL.Opt(IDL.Nat),
  'vehicleId' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const VisitorStats = IDL.Record({
  'totalVisitors' : IDL.Nat,
  'weeklyVisitors' : IDL.Nat,
  'monthlyVisitors' : IDL.Nat,
  'dailyVisitors' : IDL.Nat,
  'pageViews' : IDL.Nat,
});
export const MediaAsset = IDL.Record({
  'id' : IDL.Nat,
  'assetId' : IDL.Text,
  'size' : IDL.Nat,
  'mimeType' : IDL.Text,
  'filename' : IDL.Text,
  'uploadedAt' : IDL.Int,
  'uploadedBy' : IDL.Principal,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createBlogPost' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Principal,
        IDL.Opt(IDL.Text),
        IDL.Bool,
        IDL.Opt(IDL.Int),
      ],
      [BlogPost],
      [],
    ),
  'createVariant' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Nat, IDL.Opt(IDL.Nat)],
      [Variant],
      [],
    ),
  'getBlogPosts' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Opt(IDL.Bool)],
      [IDL.Vec(BlogPost)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVisitorStats' : IDL.Func([], [VisitorStats], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'trackPageView' : IDL.Func([], [], []),
  'trackVisitor' : IDL.Func([], [], []),
  'updateBlogPost' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Principal,
        IDL.Opt(IDL.Text),
        IDL.Bool,
        IDL.Opt(IDL.Int),
      ],
      [IDL.Opt(BlogPost)],
      [],
    ),
  'uploadMediaAsset' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
      [MediaAsset],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const BlogPost = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'authorId' : IDL.Principal,
    'published' : IDL.Bool,
    'createdAt' : IDL.Int,
    'publishedAt' : IDL.Opt(IDL.Int),
    'updatedAt' : IDL.Int,
    'excerpt' : IDL.Text,
    'imageId' : IDL.Opt(IDL.Text),
  });
  const Variant = IDL.Record({
    'id' : IDL.Nat,
    'displayOrder' : IDL.Nat,
    'name' : IDL.Text,
    'overridePrice' : IDL.Opt(IDL.Nat),
    'vehicleId' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const VisitorStats = IDL.Record({
    'totalVisitors' : IDL.Nat,
    'weeklyVisitors' : IDL.Nat,
    'monthlyVisitors' : IDL.Nat,
    'dailyVisitors' : IDL.Nat,
    'pageViews' : IDL.Nat,
  });
  const MediaAsset = IDL.Record({
    'id' : IDL.Nat,
    'assetId' : IDL.Text,
    'size' : IDL.Nat,
    'mimeType' : IDL.Text,
    'filename' : IDL.Text,
    'uploadedAt' : IDL.Int,
    'uploadedBy' : IDL.Principal,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createBlogPost' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Principal,
          IDL.Opt(IDL.Text),
          IDL.Bool,
          IDL.Opt(IDL.Int),
        ],
        [BlogPost],
        [],
      ),
    'createVariant' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Nat, IDL.Opt(IDL.Nat)],
        [Variant],
        [],
      ),
    'getBlogPosts' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Opt(IDL.Bool)],
        [IDL.Vec(BlogPost)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVisitorStats' : IDL.Func([], [VisitorStats], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'trackPageView' : IDL.Func([], [], []),
    'trackVisitor' : IDL.Func([], [], []),
    'updateBlogPost' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Principal,
          IDL.Opt(IDL.Text),
          IDL.Bool,
          IDL.Opt(IDL.Int),
        ],
        [IDL.Opt(BlogPost)],
        [],
      ),
    'uploadMediaAsset' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [MediaAsset],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };