/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminRecord {
  'principal' : Principal,
  'createdAt' : bigint,
  'role' : UserRole,
  'updatedAt' : bigint,
}
export interface BannerImage {
  'id' : bigint,
  'bannerType' : BannerImageType,
  'data' : Uint8Array,
  'size' : bigint,
  'mimeType' : string,
  'filename' : string,
  'uploadedAt' : bigint,
  'uploadedBy' : Principal,
}
export type BannerImageType = { 'mainBanner' : null } |
  { 'ctaBanner' : null };
export interface MediaAsset {
  'id' : bigint,
  'data' : Uint8Array,
  'size' : bigint,
  'mimeType' : string,
  'filename' : string,
  'uploadedAt' : bigint,
  'uploadedBy' : Principal,
}
export interface UserProfile {
  'name' : string,
  'email' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'super_admin' : null };
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Visit {
  'id' : string,
  'referrer' : string,
  'visitedAt' : bigint,
  'pageUrl' : string,
  'deviceType' : string,
  'browser' : string,
  'sessionId' : string,
  'userAgent' : string,
  'ipAddress' : string,
}
export interface VisitorSession {
  'lastActivity' : bigint,
  'isOnline' : boolean,
  'firstVisit' : bigint,
  'sessionId' : string,
  'ipAddress' : string,
}
export interface VisitorStats {
  'visitorsThisWeek' : bigint,
  'visitorsYesterday' : bigint,
  'visitorsThisYear' : bigint,
  'onlineNow' : bigint,
  'totalVisitors' : bigint,
  'visitorsToday' : bigint,
  'pageViewsToday' : bigint,
  'visitorsThisMonth' : bigint,
}
export interface WebsiteSettings {
  'mainBannerImageId' : [] | [bigint],
  'dealerAddress' : string,
  'operationalHours' : string,
  'lastUpdated' : bigint,
  'instagramUrl' : string,
  'ctaBannerImageId' : [] | [bigint],
  'siteName' : string,
  'contactEmail' : string,
  'contactWhatsapp' : string,
  'youtubeUrl' : string,
  'facebookUrl' : string,
  'contactPhone' : string,
  'tiktokUrl' : string,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  'cleanupExpiredSessions' : ActorMethod<[], undefined>,
  'deleteAdmin' : ActorMethod<[Principal], undefined>,
  'deleteMediaAsset' : ActorMethod<[bigint], boolean>,
  'forceSetMeAsSuperAdmin' : ActorMethod<[], string>,
  'getAdmins' : ActorMethod<[], Array<AdminRecord>>,
  'getAllMediaAssets' : ActorMethod<[], Array<MediaAsset>>,
  'getAllVisitorSessions' : ActorMethod<[], Array<VisitorSession>>,
  'getAllVisits' : ActorMethod<[], Array<Visit>>,
  'getAssetsByDateRange' : ActorMethod<[bigint, bigint], Array<MediaAsset>>,
  'getAssetsByUploader' : ActorMethod<[Principal], Array<MediaAsset>>,
  'getBannerImages' : ActorMethod<[], Array<BannerImage>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  'getDailyVisitorTrend' : ActorMethod<[], Array<[bigint, bigint]>>,
  'getMediaAssetByBlobId' : ActorMethod<[string], [] | [MediaAsset]>,
  'getMediaAssetById' : ActorMethod<[bigint], [] | [MediaAsset]>,
  'getMediaAssets' : ActorMethod<[], Array<MediaAsset>>,
  'getMyRole' : ActorMethod<[], [] | [UserRole]>,
  'getOnlineUsers' : ActorMethod<[], bigint>,
  'getPublicVisitorStats' : ActorMethod<[], VisitorStats>,
  'getStableVisitorStats' : ActorMethod<[], VisitorStats>,
  'getTopPageViews' : ActorMethod<[], Array<[string, bigint]>>,
  'getTotalPageViews' : ActorMethod<[], bigint>,
  'getTotalVisitors' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVisitorStats' : ActorMethod<[], VisitorStats>,
  'getWebsiteSettings' : ActorMethod<[], WebsiteSettings>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'periodicCleanup' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'trackVisitor' : ActorMethod<
    [string, string, string, string, string, string, string],
    undefined
  >,
  'updateAdminRole' : ActorMethod<[Principal, UserRole], undefined>,
  'updateMediaAsset' : ActorMethod<
    [bigint, string, string, Uint8Array, bigint],
    undefined
  >,
  'updateWebsiteSettings' : ActorMethod<[WebsiteSettings], undefined>,
  'uploadBannerImage' : ActorMethod<
    [string, BannerImageType, string, Uint8Array, bigint],
    bigint
  >,
  'uploadMediaAsset' : ActorMethod<
    [string, string, Uint8Array, bigint],
    undefined
  >,
  'whoAmI' : ActorMethod<[], string>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];