/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface UserProfile {
    name: string;
    email: string;
    phone: string;
}
export interface AdminUser {
    principal: Principal;
    name: string;
    createdAt: bigint;
    role: UserRole;
    email: string;
}
export interface MediaAsset {
    id: bigint;
    data: Uint8Array;
    size: bigint;
    mimeType: string;
    filename: string;
    uploadedAt: bigint;
    uploadedBy: Principal;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface BannerImage {
    id: bigint;
    bannerType: BannerImageType;
    data: Uint8Array;
    size: bigint;
    mimeType: string;
    filename: string;
    uploadedAt: bigint;
    uploadedBy: Principal;
}
export interface VisitorSession {
    lastActivity: bigint;
    isOnline: boolean;
    firstVisit: bigint;
    sessionId: string;
    ipAddress: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface VisitorStats {
    visitorsThisWeek: bigint;
    visitorsYesterday: bigint;
    visitorsThisYear: bigint;
    onlineNow: bigint;
    totalVisitors: bigint;
    visitorsToday: bigint;
    pageViewsToday: bigint;
    visitorsThisMonth: bigint;
}
export interface Visit {
    id: string;
    referrer: string;
    visitedAt: bigint;
    pageUrl: string;
    deviceType: string;
    browser: string;
    sessionId: string;
    userAgent: string;
    ipAddress: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface WebsiteSettings {
    mainBannerImageId?: bigint;
    dealerAddress: string;
    operationalHours: string;
    lastUpdated: bigint;
    instagramUrl: string;
    ctaBannerImageId?: bigint;
    siteName: string;
    contactEmail: string;
    contactWhatsapp: string;
    youtubeUrl: string;
    facebookUrl: string;
    contactPhone: string;
    tiktokUrl: string;
}
export enum BannerImageType {
    mainBanner = "mainBanner",
    ctaBanner = "ctaBanner"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    cleanupExpiredSessions(): Promise<void>;
    createAdminUser(name: string, email: string, role: UserRole): Promise<AdminUser>;
    deleteMediaAsset(id: bigint): Promise<boolean>;
    getAllAdminUsers(): Promise<Array<AdminUser>>;
    getAllMediaAssets(): Promise<Array<MediaAsset>>;
    getAllVisitorSessions(): Promise<Array<VisitorSession>>;
    getAllVisits(): Promise<Array<Visit>>;
    getAssetsByDateRange(startDate: bigint, endDate: bigint): Promise<Array<MediaAsset>>;
    getAssetsByUploader(uploader: Principal): Promise<Array<MediaAsset>>;
    getBannerImages(): Promise<Array<BannerImage>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getMediaAssetByBlobId(blobId: string): Promise<MediaAsset | null>;
    getMediaAssetById(id: bigint): Promise<MediaAsset | null>;
    getMediaAssets(): Promise<Array<MediaAsset>>;
    getOnlineUsers(): Promise<bigint>;
    getStableVisitorStats(): Promise<VisitorStats>;
    getTotalPageViews(): Promise<bigint>;
    getTotalVisitors(): Promise<bigint>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getVisitorStats(): Promise<VisitorStats>;
    getWebsiteSettings(): Promise<WebsiteSettings>;
    isCallerAdmin(): Promise<boolean>;
    periodicCleanup(): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    trackVisitor(sessionId: string, ipAddress: string, userAgent: string, pageUrl: string, referrer: string, deviceType: string, browser: string): Promise<void>;
    updateMediaAsset(id: bigint, newFilename: string, newMimeType: string, newData: Uint8Array, newSize: bigint): Promise<void>;
    updateWebsiteSettings(newSettings: WebsiteSettings): Promise<void>;
    uploadBannerImage(filename: string, bannerType: BannerImageType, mimeType: string, data: Uint8Array, fileSize: bigint): Promise<bigint>;
    uploadMediaAsset(filename: string, mimeType: string, data: Uint8Array, fileSize: bigint): Promise<void>;
}
import type { AdminUser as _AdminUser, BannerImage as _BannerImage, BannerImageType as _BannerImageType, MediaAsset as _MediaAsset, UserProfile as _UserProfile, UserRole as _UserRole, WebsiteSettings as _WebsiteSettings, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async cleanupExpiredSessions(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.cleanupExpiredSessions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cleanupExpiredSessions();
            return result;
        }
    }
    async createAdminUser(arg0: string, arg1: string, arg2: UserRole): Promise<AdminUser> {
        if (this.processError) {
            try {
                const result = await this.actor.createAdminUser(arg0, arg1, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg2));
                return from_candid_AdminUser_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAdminUser(arg0, arg1, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg2));
            return from_candid_AdminUser_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteMediaAsset(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMediaAsset(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMediaAsset(arg0);
            return result;
        }
    }
    async getAllAdminUsers(): Promise<Array<AdminUser>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAdminUsers();
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAdminUsers();
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllMediaAssets(): Promise<Array<MediaAsset>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMediaAssets();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMediaAssets();
            return result;
        }
    }
    async getAllVisitorSessions(): Promise<Array<VisitorSession>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllVisitorSessions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllVisitorSessions();
            return result;
        }
    }
    async getAllVisits(): Promise<Array<Visit>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllVisits();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllVisits();
            return result;
        }
    }
    async getAssetsByDateRange(arg0: bigint, arg1: bigint): Promise<Array<MediaAsset>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAssetsByDateRange(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAssetsByDateRange(arg0, arg1);
            return result;
        }
    }
    async getAssetsByUploader(arg0: Principal): Promise<Array<MediaAsset>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAssetsByUploader(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAssetsByUploader(arg0);
            return result;
        }
    }
    async getBannerImages(): Promise<Array<BannerImage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBannerImages();
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBannerImages();
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMediaAssetByBlobId(arg0: string): Promise<MediaAsset | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMediaAssetByBlobId(arg0);
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMediaAssetByBlobId(arg0);
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMediaAssetById(arg0: bigint): Promise<MediaAsset | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMediaAssetById(arg0);
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMediaAssetById(arg0);
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMediaAssets(): Promise<Array<MediaAsset>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMediaAssets();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMediaAssets();
            return result;
        }
    }
    async getOnlineUsers(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getOnlineUsers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOnlineUsers();
            return result;
        }
    }
    async getStableVisitorStats(): Promise<VisitorStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getStableVisitorStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStableVisitorStats();
            return result;
        }
    }
    async getTotalPageViews(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalPageViews();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalPageViews();
            return result;
        }
    }
    async getTotalVisitors(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalVisitors();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalVisitors();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVisitorStats(): Promise<VisitorStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getVisitorStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVisitorStats();
            return result;
        }
    }
    async getWebsiteSettings(): Promise<WebsiteSettings> {
        if (this.processError) {
            try {
                const result = await this.actor.getWebsiteSettings();
                return from_candid_WebsiteSettings_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWebsiteSettings();
            return from_candid_WebsiteSettings_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async periodicCleanup(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.periodicCleanup();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.periodicCleanup();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async trackVisitor(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.trackVisitor(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.trackVisitor(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async updateMediaAsset(arg0: bigint, arg1: string, arg2: string, arg3: Uint8Array, arg4: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMediaAsset(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMediaAsset(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async updateWebsiteSettings(arg0: WebsiteSettings): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateWebsiteSettings(to_candid_WebsiteSettings_n24(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateWebsiteSettings(to_candid_WebsiteSettings_n24(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async uploadBannerImage(arg0: string, arg1: BannerImageType, arg2: string, arg3: Uint8Array, arg4: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadBannerImage(arg0, to_candid_BannerImageType_n26(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadBannerImage(arg0, to_candid_BannerImageType_n26(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4);
            return result;
        }
    }
    async uploadMediaAsset(arg0: string, arg1: string, arg2: Uint8Array, arg3: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadMediaAsset(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadMediaAsset(arg0, arg1, arg2, arg3);
            return result;
        }
    }
}
function from_candid_AdminUser_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AdminUser): AdminUser {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_BannerImageType_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BannerImageType): BannerImageType {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_BannerImage_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BannerImage): BannerImage {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_WebsiteSettings_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WebsiteSettings): WebsiteSettings {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MediaAsset]): MediaAsset | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    principal: Principal;
    name: string;
    createdAt: bigint;
    role: _UserRole;
    email: string;
}): {
    principal: Principal;
    name: string;
    createdAt: bigint;
    role: UserRole;
    email: string;
} {
    return {
        principal: value.principal,
        name: value.name,
        createdAt: value.createdAt,
        role: from_candid_UserRole_n12(_uploadFile, _downloadFile, value.role),
        email: value.email
    };
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    bannerType: _BannerImageType;
    data: Uint8Array;
    size: bigint;
    mimeType: string;
    filename: string;
    uploadedAt: bigint;
    uploadedBy: Principal;
}): {
    id: bigint;
    bannerType: BannerImageType;
    data: Uint8Array;
    size: bigint;
    mimeType: string;
    filename: string;
    uploadedAt: bigint;
    uploadedBy: Principal;
} {
    return {
        id: value.id,
        bannerType: from_candid_BannerImageType_n18(_uploadFile, _downloadFile, value.bannerType),
        data: value.data,
        size: value.size,
        mimeType: value.mimeType,
        filename: value.filename,
        uploadedAt: value.uploadedAt,
        uploadedBy: value.uploadedBy
    };
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    mainBannerImageId: [] | [bigint];
    dealerAddress: string;
    operationalHours: string;
    lastUpdated: bigint;
    instagramUrl: string;
    ctaBannerImageId: [] | [bigint];
    siteName: string;
    contactEmail: string;
    contactWhatsapp: string;
    youtubeUrl: string;
    facebookUrl: string;
    contactPhone: string;
    tiktokUrl: string;
}): {
    mainBannerImageId?: bigint;
    dealerAddress: string;
    operationalHours: string;
    lastUpdated: bigint;
    instagramUrl: string;
    ctaBannerImageId?: bigint;
    siteName: string;
    contactEmail: string;
    contactWhatsapp: string;
    youtubeUrl: string;
    facebookUrl: string;
    contactPhone: string;
    tiktokUrl: string;
} {
    return {
        mainBannerImageId: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.mainBannerImageId)),
        dealerAddress: value.dealerAddress,
        operationalHours: value.operationalHours,
        lastUpdated: value.lastUpdated,
        instagramUrl: value.instagramUrl,
        ctaBannerImageId: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.ctaBannerImageId)),
        siteName: value.siteName,
        contactEmail: value.contactEmail,
        contactWhatsapp: value.contactWhatsapp,
        youtubeUrl: value.youtubeUrl,
        facebookUrl: value.facebookUrl,
        contactPhone: value.contactPhone,
        tiktokUrl: value.tiktokUrl
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    mainBanner: null;
} | {
    ctaBanner: null;
}): BannerImageType {
    return "mainBanner" in value ? BannerImageType.mainBanner : "ctaBanner" in value ? BannerImageType.ctaBanner : value;
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AdminUser>): Array<AdminUser> {
    return value.map((x)=>from_candid_AdminUser_n10(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BannerImage>): Array<BannerImage> {
    return value.map((x)=>from_candid_BannerImage_n16(_uploadFile, _downloadFile, x));
}
function to_candid_BannerImageType_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BannerImageType): _BannerImageType {
    return to_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_WebsiteSettings_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: WebsiteSettings): _WebsiteSettings {
    return to_candid_record_n25(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    mainBannerImageId?: bigint;
    dealerAddress: string;
    operationalHours: string;
    lastUpdated: bigint;
    instagramUrl: string;
    ctaBannerImageId?: bigint;
    siteName: string;
    contactEmail: string;
    contactWhatsapp: string;
    youtubeUrl: string;
    facebookUrl: string;
    contactPhone: string;
    tiktokUrl: string;
}): {
    mainBannerImageId: [] | [bigint];
    dealerAddress: string;
    operationalHours: string;
    lastUpdated: bigint;
    instagramUrl: string;
    ctaBannerImageId: [] | [bigint];
    siteName: string;
    contactEmail: string;
    contactWhatsapp: string;
    youtubeUrl: string;
    facebookUrl: string;
    contactPhone: string;
    tiktokUrl: string;
} {
    return {
        mainBannerImageId: value.mainBannerImageId ? candid_some(value.mainBannerImageId) : candid_none(),
        dealerAddress: value.dealerAddress,
        operationalHours: value.operationalHours,
        lastUpdated: value.lastUpdated,
        instagramUrl: value.instagramUrl,
        ctaBannerImageId: value.ctaBannerImageId ? candid_some(value.ctaBannerImageId) : candid_none(),
        siteName: value.siteName,
        contactEmail: value.contactEmail,
        contactWhatsapp: value.contactWhatsapp,
        youtubeUrl: value.youtubeUrl,
        facebookUrl: value.facebookUrl,
        contactPhone: value.contactPhone,
        tiktokUrl: value.tiktokUrl
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BannerImageType): {
    mainBanner: null;
} | {
    ctaBanner: null;
} {
    return value == BannerImageType.mainBanner ? {
        mainBanner: null
    } : value == BannerImageType.ctaBanner ? {
        ctaBanner: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
